const { Post } = require('../models');

const postData = [
  {
    title: 'test title 1',
    summary: 'Here is a summary 1',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum morbi blandit cursus risus at ultrices mi. Donec massa sapien faucibus et molestie ac feugiat. Massa ultricies mi quis hendrerit dolor magna. Est velit egestas dui id ornare arcu odio. Mauris augue neque gravida in fermentum et sollicitudin. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tristique nulla aliquet enim tortor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Vitae proin sagittis nisl rhoncus mattis. Arcu cursus euismod quis viverra nibh cras. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Convallis convallis tellus id interdum velit laoreet id donec.Sit amet venenatis urna cursus eget.Urna molestie at elementum eu facilisis sed odio morbi.Ac feugiat sed lectus vestibulum mattis ullamcorper velit.Imperdiet proin fermentum leo vel orci porta.Adipiscing elit pellentesque habitant morbi tristique senectus et netus.Massa sapien faucibus et molestie ac feugiat.Cras fermentum odio eu feugiat pretium.Nulla aliquet porttitor lacus luctus accumsan tortor.Varius quam quisque id diam vel quam.In fermentum et sollicitudin ac orci phasellus.Nec feugiat nisl pretium fusce id velit ut tortor pretium.Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere.Orci eu lobortis elementum nibh tellus molestie nunc.Viverra justo nec ultrices dui sapien eget mi proin.Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lobortis mattis aliquam faucibus purus in massa tempor nec.Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.Ut morbi tincidunt augue interdum velit euismod in.Egestas quis ipsum suspendisse ultrices gravida dictum.Venenatis cras sed felis eget velit aliquet sagittis.Nunc sed id semper risus.Aliquam etiam erat velit scelerisque in dictum.Libero id faucibus nisl tincidunt eget nullam non nisi est.Amet tellus cras adipiscing enim.Lacus sed turpis tincidunt id aliquet risus.Odio facilisis mauris sit amet massa vitae.Eu sem integer vitae justo eget magna fermentum iaculis eu.Feugiat in ante metus dictum at tempor commodo ullamcorper.Non nisi est sit amet facilisis magna.', 
    user_id: 2,
    createdAt: '2023-01-01 11:15:33'
  },
  {
    title: 'test title 2',
    summary: 'Here is a summary 2',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum morbi blandit cursus risus at ultrices mi. Donec massa sapien faucibus et molestie ac feugiat. Massa ultricies mi quis hendrerit dolor magna. Est velit egestas dui id ornare arcu odio. Mauris augue neque gravida in fermentum et sollicitudin. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tristique nulla aliquet enim tortor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Vitae proin sagittis nisl rhoncus mattis. Arcu cursus euismod quis viverra nibh cras. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Convallis convallis tellus id interdum velit laoreet id donec.Sit amet venenatis urna cursus eget.Urna molestie at elementum eu facilisis sed odio morbi.Ac feugiat sed lectus vestibulum mattis ullamcorper velit.Imperdiet proin fermentum leo vel orci porta.Adipiscing elit pellentesque habitant morbi tristique senectus et netus.Massa sapien faucibus et molestie ac feugiat.Cras fermentum odio eu feugiat pretium.Nulla aliquet porttitor lacus luctus accumsan tortor.Varius quam quisque id diam vel quam.In fermentum et sollicitudin ac orci phasellus.Nec feugiat nisl pretium fusce id velit ut tortor pretium.Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere.Orci eu lobortis elementum nibh tellus molestie nunc.Viverra justo nec ultrices dui sapien eget mi proin.Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lobortis mattis aliquam faucibus purus in massa tempor nec.Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.Ut morbi tincidunt augue interdum velit euismod in.Egestas quis ipsum suspendisse ultrices gravida dictum.Venenatis cras sed felis eget velit aliquet sagittis.Nunc sed id semper risus.Aliquam etiam erat velit scelerisque in dictum.Libero id faucibus nisl tincidunt eget nullam non nisi est.Amet tellus cras adipiscing enim.Lacus sed turpis tincidunt id aliquet risus.Odio facilisis mauris sit amet massa vitae.Eu sem integer vitae justo eget magna fermentum iaculis eu.Feugiat in ante metus dictum at tempor commodo ullamcorper.Non nisi est sit amet facilisis magna.', 
    user_id: 4,
    createdAt: '2023-01-08 14:46:14'
  },
  {
    title: 'test title 3',
    summary: 'Here is a summary 3',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum morbi blandit cursus risus at ultrices mi. Donec massa sapien faucibus et molestie ac feugiat. Massa ultricies mi quis hendrerit dolor magna. Est velit egestas dui id ornare arcu odio. Mauris augue neque gravida in fermentum et sollicitudin. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tristique nulla aliquet enim tortor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Vitae proin sagittis nisl rhoncus mattis. Arcu cursus euismod quis viverra nibh cras. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Convallis convallis tellus id interdum velit laoreet id donec.Sit amet venenatis urna cursus eget.Urna molestie at elementum eu facilisis sed odio morbi.Ac feugiat sed lectus vestibulum mattis ullamcorper velit.Imperdiet proin fermentum leo vel orci porta.Adipiscing elit pellentesque habitant morbi tristique senectus et netus.Massa sapien faucibus et molestie ac feugiat.Cras fermentum odio eu feugiat pretium.Nulla aliquet porttitor lacus luctus accumsan tortor.Varius quam quisque id diam vel quam.In fermentum et sollicitudin ac orci phasellus.Nec feugiat nisl pretium fusce id velit ut tortor pretium.Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere.Orci eu lobortis elementum nibh tellus molestie nunc.Viverra justo nec ultrices dui sapien eget mi proin.Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lobortis mattis aliquam faucibus purus in massa tempor nec.Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.Ut morbi tincidunt augue interdum velit euismod in.Egestas quis ipsum suspendisse ultrices gravida dictum.Venenatis cras sed felis eget velit aliquet sagittis.Nunc sed id semper risus.Aliquam etiam erat velit scelerisque in dictum.Libero id faucibus nisl tincidunt eget nullam non nisi est.Amet tellus cras adipiscing enim.Lacus sed turpis tincidunt id aliquet risus.Odio facilisis mauris sit amet massa vitae.Eu sem integer vitae justo eget magna fermentum iaculis eu.Feugiat in ante metus dictum at tempor commodo ullamcorper.Non nisi est sit amet facilisis magna.', 
    user_id: 3,
    createdAt: '2023-01-16 19:55:27'
  },
  {
    title: 'Ultimate Heroku Guide',
    summary: 'This guide is here for beginners to advanced users of Heroku deployment',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum morbi blandit cursus risus at ultrices mi. Donec massa sapien faucibus et molestie ac feugiat. Massa ultricies mi quis hendrerit dolor magna. Est velit egestas dui id ornare arcu odio. Mauris augue neque gravida in fermentum et sollicitudin. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tristique nulla aliquet enim tortor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Vitae proin sagittis nisl rhoncus mattis. Arcu cursus euismod quis viverra nibh cras. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Convallis convallis tellus id interdum velit laoreet id donec.Sit amet venenatis urna cursus eget.Urna molestie at elementum eu facilisis sed odio morbi.Ac feugiat sed lectus vestibulum mattis ullamcorper velit.Imperdiet proin fermentum leo vel orci porta.Adipiscing elit pellentesque habitant morbi tristique senectus et netus.Massa sapien faucibus et molestie ac feugiat.Cras fermentum odio eu feugiat pretium.Nulla aliquet porttitor lacus luctus accumsan tortor.Varius quam quisque id diam vel quam.In fermentum et sollicitudin ac orci phasellus.Nec feugiat nisl pretium fusce id velit ut tortor pretium.Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere.Orci eu lobortis elementum nibh tellus molestie nunc.Viverra justo nec ultrices dui sapien eget mi proin.Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lobortis mattis aliquam faucibus purus in massa tempor nec.Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.Ut morbi tincidunt augue interdum velit euismod in.Egestas quis ipsum suspendisse ultrices gravida dictum.Venenatis cras sed felis eget velit aliquet sagittis.Nunc sed id semper risus.Aliquam etiam erat velit scelerisque in dictum.Libero id faucibus nisl tincidunt eget nullam non nisi est.Amet tellus cras adipiscing enim.Lacus sed turpis tincidunt id aliquet risus.Odio facilisis mauris sit amet massa vitae.Eu sem integer vitae justo eget magna fermentum iaculis eu.Feugiat in ante metus dictum at tempor commodo ullamcorper.Non nisi est sit amet facilisis magna.', 
    user_id: 6, 
    createdAt: '2023-01-16 19:55:27'
  },
  {
    title: 'To asynchronous or to not synchronous',
    summary: 'The pros and cons to coding with asynchronous functions.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum morbi blandit cursus risus at ultrices mi. Donec massa sapien faucibus et molestie ac feugiat. Massa ultricies mi quis hendrerit dolor magna. Est velit egestas dui id ornare arcu odio. Mauris augue neque gravida in fermentum et sollicitudin. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tristique nulla aliquet enim tortor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Vitae proin sagittis nisl rhoncus mattis. Arcu cursus euismod quis viverra nibh cras. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Convallis convallis tellus id interdum velit laoreet id donec.Sit amet venenatis urna cursus eget.Urna molestie at elementum eu facilisis sed odio morbi.Ac feugiat sed lectus vestibulum mattis ullamcorper velit.Imperdiet proin fermentum leo vel orci porta.Adipiscing elit pellentesque habitant morbi tristique senectus et netus.Massa sapien faucibus et molestie ac feugiat.Cras fermentum odio eu feugiat pretium.Nulla aliquet porttitor lacus luctus accumsan tortor.Varius quam quisque id diam vel quam.In fermentum et sollicitudin ac orci phasellus.Nec feugiat nisl pretium fusce id velit ut tortor pretium.Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere.Orci eu lobortis elementum nibh tellus molestie nunc.Viverra justo nec ultrices dui sapien eget mi proin.Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lobortis mattis aliquam faucibus purus in massa tempor nec.Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.Ut morbi tincidunt augue interdum velit euismod in.Egestas quis ipsum suspendisse ultrices gravida dictum.Venenatis cras sed felis eget velit aliquet sagittis.Nunc sed id semper risus.Aliquam etiam erat velit scelerisque in dictum.Libero id faucibus nisl tincidunt eget nullam non nisi est.Amet tellus cras adipiscing enim.Lacus sed turpis tincidunt id aliquet risus.Odio facilisis mauris sit amet massa vitae.Eu sem integer vitae justo eget magna fermentum iaculis eu.Feugiat in ante metus dictum at tempor commodo ullamcorper.Non nisi est sit amet facilisis magna.',
    user_id: 6,
    createdAt: '2023-01-23 09:55:27'
  }
];

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;